"""
This module implements a batch captioning interface for the Qwen 8B vision model 
using the vLLM engine. It is optimized for structured extraction of visual 
descriptions, identified entities, and text transcriptions from images.
"""

import os
from vllm import LLM, SamplingParams
from transformers import AutoProcessor
from qwen_vl_utils import process_vision_info

# Required for multiprocessing support in vLLM for vision-language models
os.environ['VLLM_WORKER_MULTIPROC_METHOD'] = 'spawn'

# Prompt designed for structured data extraction
CAPTION_PROMPT = """
Analyse the image and return ONLY these four sections, no extra text.

VISUAL_DESCRIPTION:
3-5 sentences describing the scene, setting, people, objects, and overall context.

ENTITIES_IDENTIFIED:
Name every identifiable person, organisation, location, flag, or symbol. 
For each: full name and type (PERSON/ORG/LOCATION/FLAG/SYMBOL). 
Attempt identification to support entity linking for news verification.
If none: NO_ENTITIES_FOUND

TEXT_TRANSCRIPTION:
Transcribe every visible text exactly in its original script. If none: NO_TEXT_FOUND

SCENE_CONTEXT:
Two sentences describing the probable event or situation shown.
"""

class QwenCaptioner:
    """Wrapper class for the Qwen model to handle model initialization and batch inference."""

    def __init__(self, model_id: str = "Qwen/Qwen3-VL-8B-Instruct"):
        print(f"Initializing vLLM Engine for {model_id}")

        # Engine configuration optimized for high-resolution vision tasks
        self.llm = LLM(
            model=model_id,
            limit_mm_per_prompt={"image": 1},
            gpu_memory_utilization=0.9,
            max_model_len=16384,
            trust_remote_code=True,
            enforce_eager=True,
            dtype="bfloat16"
        )

        self.processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

        # Greedy decoding (temperature 0) used for deterministic structured output
        self.sampling_params = SamplingParams(
            temperature=0.0,
            max_tokens=512,
            stop=["<|im_end|>", "<|endoftext|>"]
        )

    def _build_prompt(self) -> str:
        """Applies the chat template to the prompt for model compatibility."""
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": "placeholder"},
                    {"type": "text", "text": CAPTION_PROMPT}
                ]
            }
        ]
        
        # Generates the prompt string with proper vision-token placeholders
        return self.processor.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False
        )

    def generate_batch_captions(self, image_paths: list[str]) -> list[str]:
        """
        Takes a list of image paths and returns a corresponding list of 
        structured captions generated by the model.
        """
        prompt_template = self._build_prompt()
        batch_inputs = []
        valid_indices = []

        for idx, path in enumerate(image_paths):
            try:
                # Preprocess image and text inputs for the specific model architecture
                messages = [
                    {
                        "role": "user",
                        "content": [
                            {"type": "image", "image": path},
                            {"type": "text", "text": CAPTION_PROMPT}
                        ]
                    }
                ]
                
                image_inputs, _, _ = process_vision_info(
                    messages,
                    image_patch_size=self.processor.image_processor.patch_size
                )

                multi_modal_data = {"image": image_inputs} if image_inputs is not None else {}
                
                batch_inputs.append({
                    "prompt": prompt_template,
                    "multi_modal_data": multi_modal_data
                })
                valid_indices.append(idx)

            except Exception as e:
                print(f"Error processing image at {path}: {e}")

        if not batch_inputs:
            return ["ERROR"] * len(image_paths)

        # Run inference across the batch
        outputs = self.llm.generate(
            batch_inputs,
            sampling_params=self.sampling_params,
            use_tqdm=False
        )

        results = ["ERROR"] * len(image_paths)
        for i, output in zip(valid_indices, outputs):
            results[i] = output.outputs[0].text.strip()

        return results
